Add basic scene and controls
JacobALundgren/rpg-system-2d pull request #2
Opened 2021-08-24 23:28 UTC by JacobALundgren

**  Behavioral change: Introduce a single world screen with a player
square. Enable WASD keyboard control of player.

Issues: [#1]

2021-08-24 23:28 UTC, JacobALundgren commented
Closes #1

2021-08-25 07:41 UTC, JacobALundgren commented
Did a force push as I stupidly forgot to run the formatter.

2021-08-28 08:04 UTC, queleok commented
It looks like there's an implicit dependency on either precompiled `shaderc` library, or `cmake`. I don't have either of those, so I got this error upon an attempt to run the package:
```
warning: shaderc: searching for native shaderc libraries on system;  use '--features build-from-source' to force building from source code
warning: shaderc: cannot find native shaderc library on system; falling back to build from source

error: failed to run custom build command for `shaderc-sys v0.7.3`

Caused by:
  process didn't exit successfully: `/Users/queleok/projects/rpg-game/target/debug/build/shaderc-sys-864c44d34bbbb17d/build-script-build` (exit status: 101)
  --- stdout
  cargo:warning=shaderc: searching for native shaderc libraries on system;  use '--features build-from-source' to force building from source code
  cargo:warning=shaderc: cannot find native shaderc library on system; falling back to build from source

  --- stderr
  thread 'main' panicked at '

  couldn't find required command: "cmake"

  ', /Users/queleok/.cargo/registry/src/github.com-1ecc6299db9ec823/shaderc-sys-0.7.3/build/cmd_finder.rs:55:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

2021-08-28 08:26 UTC, queleok commented on Cargo.toml
> +bevy = { version = "0.5.0", features = ["dynamic"] }
How about adding a build dependency (not so sure about the exact version, just added mine)?
```
[build-dependencies]
cmake = 3.21.2
```

2021-08-28 09:03 UTC, queleok requested changes
Please, check the suggestion for `Cargo.toml`

2021-08-28 10:12 UTC, JacobALundgren commented
As discussed elsewhere, this seems to be [an issue in Bevy](https://github.com/bevyengine/bevy/issues/1360). Added a note suggesting the installation of cmake or the Vulkan SDK

2021-08-28 10:18 UTC, queleok approved these changes
Thank you, everything looks great :)

2021-08-28 12:46 UTC, merged